require('admin-lte/plugins/datatables/jquery.dataTables')
require('admin-lte/plugins/datatables-responsive/js/dataTables.responsive')
require('admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4')
require('admin-lte/plugins/datatables-buttons/js/dataTables.buttons')
require('admin-lte/plugins/datatables-buttons/js/buttons.bootstrap4')